In [1]:
import pandas as pd

In [2]:
nursing_homes_df=pd.read_csv("Nursing-homes-geocodes - Sheet1.csv")
#https://mhcc.maryland.gov/public-use-files/download?token=p0Wuv8o8J_Be-NjiyGxjb-gKZlEPo1i65F7bTVwr17E

In [3]:
nursing_homes_df

,Current Name,Facility Street1,Facility City,Facility State,Facility Zip Code,Latitude,Longitude
0,Allegany Health Nursing and Rehabilitation Cent,730 Furnace Street,Cumberland,MD,21502,39.668600,-78.764110
1,Cumberland Healthcare Center,512 Winifred Road,Cumberland,MD,21502,39.645685,-78.743063
2,"Egle Nursing Home Management, Inc.",57 Jackson Street,Lonaconing,MD,21539,39.562944,-78.978701
3,Lions Rehab Center,901 Seton Drive,Cumberland,MD,21502,39.656895,-78.794236
4,Frostburg Rehab Center,1 Kaylor Circle,Frostburg,MD,21532,39.645679,-78.907445
...,...,...,...,...,...,...,...
215,FutureCare Lochearn,4800 Seton Drive,Baltimore,MD,21215,39.342262,-76.708793
216,FutureCare Sandtown,1000 North Gilmor Street,Baltimore,MD,21217,39.300078,-76.643111
217,Westgate Hills Rehabilitation & Healthcare Cent,10 N. Rock Glen Road,Baltimore,MD,21229,39.284314,-76.700865
218,FutureCare Charles Village,2327 N. Charles Street,Baltimore,MD,21218,39.315602,-76.616792
219,The Nursing and Rehabilitation Center at Stadiu,1010 East 33rd Street,Baltimore,MD,21218,39.328582,-76.602358

In [4]:
nursing_homes_df=nursing_homes_df.rename(columns={'Facility Zip Code': 'Zip Code'})

In [5]:
zip_codes_county_md_df = pd.read_csv("Zip_Code_Lookup_Table_20260731.csv")

In [6]:
zip_codes_county_md_df

     Zip Code        City               County
0       20601     Waldorf       Charles County
1       20602     Waldorf       Charles County
2       20603     Waldorf       Charles County
3       20604     Waldorf       Charles County
4       20606       Abell  Saint Mary's County
..        ...         ...                  ...
614     21919  Earleville         Cecil County
615     21920   Elk Mills         Cecil County
616     21921      Elkton         Cecil County
617     21922      Elkton         Cecil County
618     21930  Georgetown         Cecil County

[619 rows x 3 columns]

In [7]:
nursing_homes_df['Zip Code'] = nursing_homes_df['Zip Code'].str.split('-').str[0]

In [8]:
nursing_homes_df['Zip Code']=nursing_homes_df['Zip Code'].astype(int)

In [9]:
nursing_homes_df = nursing_homes_df.merge(zip_codes_county_md_df[['Zip Code', 'County']],
                                          on='Zip Code',
                                          how='left')

In [34]:
pd.set_option('display.max_rows', None)
nursing_homes_df

,Current Name,Facility Street1,Facility City,Facility State,Zip Code,Latitude,Longitude,Geographic Area Name,total_65_pct
0,Allegany Health Nursing and Rehabilitation Cent,730 Furnace Street,Cumberland,MD,21502,39.668600,-78.764110,"Allegany County, Maryland",21.14
1,Cumberland Healthcare Center,512 Winifred Road,Cumberland,MD,21502,39.645685,-78.743063,"Allegany County, Maryland",21.14
2,"Egle Nursing Home Management, Inc.",57 Jackson Street,Lonaconing,MD,21539,39.562944,-78.978701,"Allegany County, Maryland",21.14
3,Lions Rehab Center,901 Seton Drive,Cumberland,MD,21502,39.656895,-78.794236,"Allegany County, Maryland",21.14
4,Frostburg Rehab Center,1 Kaylor Circle,Frostburg,MD,21532,39.645679,-78.907445,"Allegany County, Maryland",21.14
5,Moran Nursing & Rehabilitation Center,"25701 Shady Lane, S.W.",Westernport,MD,21562,39.499995,-79.049815,"Allegany County, Maryland",21.14
6,Devlin Manor Nursing and Rehabilitation,10301 Christie Road N.E.,Cumberland,MD,21502,39.666180,-78.719890,"Allegany County, Maryland",21.14
7,Mountain City Rehab Center,48 Tarn Terrace,Frostburg,MD,21532,39.659504,-78.927474,"Allegany County, Maryland",21.14
8,Ginger Cove,4000 River Crescent Drive,Annapolis,MD,21401,38.960470,-76.558830,"Anne Arundel County, Maryland",15.86
9,Complete Care at Annapolis,900 Van Buren Street,Annapolis,MD,21403,38.961425,-76.491098,"Anne Arundel County, Maryland",15.86
10,FutureCare- Chesapeake,305 College Parkway,Arnold,MD,21012,39.049336,-76.504085,"Anne Arundel County, Maryland",15.86
11,Crownsville Health Care,1454 Fairfield Loop Road,Crownsville,MD,21032,39.027756,-76.605762,"Anne Arundel County, Maryland",15.86
12,Genesis Hammonds Lane Center,613 Hammonds Lane,Brooklyn Park,MD,21225,39.212320,-76.626886,"Baltimore city, Maryland",15.28
13,Autumn Lake Healthcare at Waugh Chapel,1221 Waugh Chapel Road,Gambrills,MD,21054,39.043123,-76.679816,"Anne Arundel County, Maryland",15.86
14,Autumn Lake Healthcare at Crofton,2131 Davidsonville Road,Crofton,MD,21114,39.011698,-76.681211,"Anne Arundel County, Maryland",15.86
15,South River Healthcare Center,144 Washington Road,Edgewater,MD,21037,38.939050,-76.559040,"Anne Arundel County, Maryland",15.86
16,Autumn Lake Healthcare at Baltimore Washington,313 Hospital Drive,Glen Burnie,MD,21061,39.139400,-76.625160,"Anne Arundel County, Maryland",15.86
17,Autumn Lake Healthcare at Glen Burnie,"7355 Furnace Branch Road, East",Glen Burnie,MD,21060,39.168480,-76.604685,"Anne Arundel County, Maryland",15.86
18,Marley Neck Health and Rehabilitation Center,7575 East Howard Road,Glen Burnie,MD,21060,39.152949,-76.583560,"Anne Arundel County, Maryland",15.86
19,Complete Care at Severna Park,310 Genesis Way,Severna Park,MD,21146,39.082032,-76.569309,"Anne Arundel County, Maryland",15.86
20,Autumn Lake Healthcare at Spa Creek,35 Milkshake Lane,Annapolis,MD,21403,38.960033,-76.503994,"Anne Arundel County, Maryland",15.86
21,The Arbor,7101 Bay Front Drive,Annapolis,MD,21403,38.963149,-76.475044,"Anne Arundel County, Maryland",15.86
22,Pickersgill Retirement Community,615 Chestnut Avenue,Towson,MD,21204,39.404974,-76.622435,"Baltimore County, Maryland",18.14
23,Resorts of Augsburg,6811 Campfield Road,Baltimore,MD,21207,39.349230,-76.725180,"Baltimore County, Maryland",18.14
24,Rossville SNF Operations LLC,6600 Ridge Road,Baltimore,MD,21237,39.342515,-76.486171,"Baltimore County, Maryland",18.14
25,Chapel Hill Nursing Center,4511 Robosson Road,Randallstown,MD,21133,39.396690,-76.860260,"Baltimore County, Maryland",18.14
26,Orchard Hill Rehabilitation and Healthcare Cent,111 West Road,Towson,MD,21204,39.410904,-76.614230,"Baltimore County, Maryland",18.14
27,"Catonsville Healthcare, LLC",701 Edmondson Avenue,Catonsville,MD,21228,39.276941,-76.733570,"Baltimore County, Maryland",18.14
28,Holly Hill Healthcare Center,531 Stevenson Lane,Towson,MD,21286,39.383860,-76.603070,"Baltimore County, Maryland",18.14
29,Advanced Rehab at Autumn Lake Healthcare,515 Brightfield Road,Lutherville,MD,21093,39.406056,-76.664767,"Baltimore County, Maryland",18.14
30,Autumn Lake Healthcare at Catonsville,16 Fusting Avenue,Catonsville,MD,21228,39.274411,-76.733643,"Baltimore County, Maryland",18.14
31,Oakwood Care Center,1300 Windlass Drive,Baltimore,MD,21220,39.335984,-76.446619,"Baltimore County, Maryland",18.14
32,Little Sisters of the Poor/St.Martin''s Home fo,601 Maiden Choice Lane,Baltimore,MD,21228,39.268945,-76.705992,"Baltimore County, Maryland",18.14
33,Autumn Lake Healthcare at Towson,7001 N. Charles Street,Towson,MD,21204,39.407054,-76.635162,"Baltimore County, Maryland",18.14
34,Towson Rehabilitation and Healthcare Center,509 East Joppa Road,Towson,MD,21286,39.401330,-76.593951,"Baltimore County, Maryland",18.14
35,"Maryland Masonic Homes, Ltd",300 International Circle,Cockeysville,MD,21030,39.497088,-76.660319,"Baltimore County, Maryland",18.14
36,King David Nursing and Rehabilitation Center,4204 Old Milford Mill Road,Baltimore,MD,21208,39.364184,-76.716140,"Baltimore County, Maryland",18.14
37,Glen Meadows Retirement Community,11630 Glen Arm Road,Glen Arm,MD,21057,39.444104,-76.509949,"Baltimore County, Maryland",18.14
38,Autumn Ridge at North Oaks,725 Mt. Wilson Lane,Baltimore,MD,21208,39.381390,-76.769120,"Baltimore County, Maryland",18.14
39,Autumn Lake Healthcare at Perring Parkway,1801 Wentworth Road,Baltimore,MD,21234,39.091429,-77.063384,"Baltimore County, Maryland",18.14
40,Autumn Lake Healthcare at Pikesville,7 Sudbrook Lane,Pikesville,MD,21208,39.030853,-77.201549,"Baltimore County, Maryland",18.14
41,Broadmead,13801 York Road,Cockeysville,MD,21030,39.067726,-76.959123,"Baltimore County, Maryland",18.14
42,Patapsco Healthcare,9109 Liberty Road,Randallstown,MD,21133,39.103591,-77.075039,"Baltimore County, Maryland",18.14
43,Ridgeway Rehabilitation Center,5743 Edmondson Avenue,Catonsville,MD,21228,39.172327,-77.208372,"Baltimore County, Maryland",18.14
44,"St. Joseph''''s Nursing Home, Inc",1222 Tugwell Drive,Catonsville,MD,21228,39.087913,-77.179126,"Baltimore County, Maryland",18.14
45,Chestnut Green Health Care Center at Blakehurst,1055 West Joppa Road,Towson,MD,21204,39.013258,-77.117294,"Baltimore County, Maryland",18.14
46,"Stella Maris, Inc.",2300 Dulaney Valley Road,Timonium,MD,21093,39.097025,-76.941387,"Baltimore County, Maryland",18.14
47,Autumn Lake Healthcare at Summit Park,1502 Frederick Road,Catonsville,MD,21228,39.029815,-77.112630,"Baltimore County, Maryland",18.14
48,Autumn Lake healthcare at Loch Raven,8720 Emge Road,Baltimore,MD,21234,39.376064,-76.559782,"Baltimore County, Maryland",18.14
49,Complete Care at Multi Medical Center,7700 York Road,Towson,MD,21204,39.373781,-76.723583,"Baltimore County, Maryland",18.14
50,Frederick villa healthcare,711 Academy Road,Catonsville,MD,21228,39.502926,-76.650014,"Baltimore County, Maryland",18.14
51,Autumn Lake Healthcare at Riverview,One Eastern Boulevard,Baltimore,MD,21221,39.369215,-76.799636,"Baltimore County, Maryland",18.14
52,"FutureCare-Old Court, LLC",5412 Old Court Road,Randallstown,MD,21133,39.281933,-76.715610,"Baltimore County, Maryland",18.14
53,FutureCare Courtland,7920 Scotts Level Road,Baltimore,MD,21208,39.258157,-76.737672,"Baltimore County, Maryland",18.14
54,Autumn Lake Healthcare at Parkville,8710 Emge Road,Baltimore,MD,21234,39.410061,-76.623701,"Baltimore County, Maryland",18.14
55,"Complete Care at Heritage Center, LLC.",7232 German Hill Road,Baltimore,MD,21222,39.450262,-76.593067,"Baltimore County, Maryland",18.14
56,FutureCare - NorthPoint,1046 Old North Point Road,Baltimore,MD,21224,39.268581,-76.747959,"Baltimore city, Maryland",15.28
57,Edenwald,800 Southerly Road,Towson,MD,21286,39.400389,-76.559423,"Baltimore County, Maryland",18.14
58,Charlestown Community Inc.,709 Maiden Choice Lane,Catonsville,MD,21228,38.762982,-76.883786,"Baltimore County, Maryland",18.14
59,FutureCare-Cherrywood,12020 Reisterstown Road,Reisterstown,MD,21136,38.951758,-76.977773,"Baltimore County, Maryland",18.14
60,Genesis Franklin Woods Center,9200 Franklin Square Drive,Baltimore,MD,21237,39.033197,-76.950814,"Baltimore County, Maryland",18.14
61,Oak Crest Village Care Center,8832 Walther Boulevard,Parkville,MD,21234,38.980943,-76.863677,"Baltimore County, Maryland",18.14
62,Meadow Park Nursing Home,1525 North Rolling Road,Catonsville,MD,21228,39.003803,-76.977301,"Baltimore County, Maryland",18.14
63,Lorien Mays Chapel,12230 Roundwood Road,Timonium,MD,21093,38.968894,-76.985514,"Baltimore County, Maryland",18.14
64,Oasis Nursing and Rehab,85 Hospital Road,Prince Frederick,MD,20678,38.847773,-76.877983,"Calvert County, Maryland",16.33
65,Solomons Skilled Nursing Center LLC,13325 Dowell Road,Solomons,MD,20688,38.958742,-76.957841,"Calvert County, Maryland",16.33
66,Asbury Atlantic Inc. dba Asbury Solomons,11750 Asbury Circle,Solomons,MD,20688,38.750515,-76.875368,"Calvert County, Maryland",16.33
67,520 Kerr Avenue Opco LLC,520 Kerr Avenue,Denton,MD,21629,38.942501,-76.824881,"Caroline County, Maryland",17.32
68,Denton Nursing and Rehab,420 Colonial Drive,Denton,MD,21629,39.387830,-76.606010,"Caroline County, Maryland",17.32
69,Fairhaven Nursing Home,7200 Third Avenue,Sykesville,MD,21784,39.286468,-76.720512,"Carroll County, Maryland",17.94
70,Atlee Hill Skilled Nursing and Rehabilitation,297 Stoner Ave,Westminster,MD,21157,39.302899,-76.487072,"Carroll County, Maryland",17.94
71,Autumn Lake Healthcare at Long View,3332 Main Street,Manchester,MD,21102,39.359617,-76.782156,"Carroll County, Maryland",17.94
72,Autumn Lake Healthcare at Birch Manor,7309 Second Avenue,Sykesville,MD,21784,39.364567,-76.749065,"Carroll County, Maryland",17.94
73,Pleasant View Healthcare Center,4101 Old National Pike,Mt. Airy,MD,21771,39.400282,-76.559368,"Frederick County, Maryland",15.29
74,Westminster Healthcare Center,1234 Washington Road,Westminster,MD,21157,39.283023,-76.518601,"Carroll County, Maryland",17.94
75,Carroll Lutheran Village Healthcare Center,200 Saint Luke Circle,Westminster,MD,21158,39.289190,-76.507842,"Carroll County, Maryland",17.94
76,Copper Ridge,710 Obrecht Road,Sykesville,MD,21784,39.378083,-76.975826,"Carroll County, Maryland",17.94
77,Lorien Mt. Airy,705 Midway Ave.,Mt. Airy,MD,21771,39.405646,-76.596449,"Frederick County, Maryland",15.29
78,Lorien - Taneytown,100 Antrim Boulevard,Taneytown,MD,21787,39.267649,-76.704119,"Carroll County, Maryland",17.94
79,Autumn Lake Healthcare at Calver Manor,1881 Telegraph Road,Rising Sun,MD,21911,38.883501,-76.813529,"Cecil County, Maryland",17.08
80,Elkton Nursing and Rehabilitation Center,One Price Drive,Elkton,MD,21921,39.087888,-76.861296,"Cecil County, Maryland",17.08
81,Laurelwood Care Center at Elkton,100 Laurel Drive,Elkton,MD,21921,38.724154,-76.988452,"Cecil County, Maryland",17.08
82,Green Acres Nursing and Rehab,10200 LaPlata Road,La Plata,MD,20646,38.764160,-76.888223,"Charles County, Maryland",13.69
83,Complete Care at La Plata,1 Magnolia Drive,La Plata,MD,20646,39.086150,-76.851044,"Charles County, Maryland",13.69
84,Genesis Waldorf Center,4140 Old Washington Highway,Waldorf,MD,20602,38.964996,-76.940718,"Charles County, Maryland",13.69
85,Restore Health Rehabilitation Center,4615 Einstein Place,White Plains,MD,20695,39.049945,-76.952158,"Charles County, Maryland",13.69
86,Mallard Bay Nursing and Rehabiliation,520 Glenburn Avenue,Cambridge,MD,21613,38.906580,-76.853024,"Dorchester County, Maryland",23.01
87,Autumn Lake Healthcare at Chesapeake Woods,525 Glenburn Avenue,Cambridge,MD,21613,39.050715,-76.061318,"Dorchester County, Maryland",23.01
88,Autumn Lake Healthcare at Ballenger Creek,347 Ballenger Center Drive,Frederick,MD,21703,38.299291,-76.636474,"Frederick County, Maryland",15.29
89,Autumn Lake Healthcare at Braddock Heights,6012 Jefferson Boulevard,Frederick,MD,21703,39.448569,-76.816155,"Frederick County, Maryland",15.29
90,Citizens Care and Rehabilitation Center of Fred,1920 Rosemont Avenue,Frederick,MD,21702,39.352951,-76.474509,"Frederick County, Maryland",15.29
91,Homewood Living Frederick,7407 Willow Road,Frederick,MD,21702,39.392684,-76.504975,"Frederick County, Maryland",15.29
92,Northampton Manor Health Care Center,200 East 16th Street,Frederick,MD,21701,39.302594,-76.753798,"Frederick County, Maryland",15.29
93,Frederick Crossing,30 North Place,Frederick,MD,21701,39.459954,-76.663678,"Frederick County, Maryland",15.29
94,Autumn Lake Healthcare at Glade Valley,56 W. Frederick Street,Walkersville,MD,21793,38.560854,-76.596532,"Frederick County, Maryland",15.29
95,Buckingham''s Choice,3200 Baker Circle,Adamstown,MD,21710,38.347318,-76.454747,"Frederick County, Maryland",15.29
96,Oakland Nursing & Rehabilitation Center,706 E Alder St,Oakland,MD,21550,38.344424,-76.466009,"Garrett County, Maryland",24.20
97,Goodwill Mennonite Home,891 Dorsey Hotel Road,Grantsville,MD,21536,38.878083,-75.826398,"Garrett County, Maryland",24.20
98,Dennett SNF LLC,1113 Mary Drive,Oakland,MD,21550,38.891868,-75.806910,"Garrett County, Maryland",24.20
99,Garrett Regional Medical Center Subacute Unit,251 North Fourth St.,Oakland,MD,21550,38.255513,-76.477807,"Garrett County, Maryland",24.20
100,Sterling Care Bel Air,410 E. MacPhail Road,Bel Air,MD,21014,38.477616,-76.777787,"Harford County, Maryland",17.45
101,Citizens Care Center,415 Market Street,Havre de Grace,MD,21078,38.209585,-75.701496,"Harford County, Maryland",17.45
102,Sterling Care Forest Hill,109 Forest Valley Drive,Forest Hill,MD,21050,37.995691,-75.852398,"Harford County, Maryland",17.45
103,Sterling Care Riverside,1123 Belcamp Garth,Belcamp,MD,21017,38.759815,-76.064577,"Harford County, Maryland",17.45
104,Lorien Nursing and Rehabilitation Center-Bel Ai,1909 Emmorton Road,Bel Air,MD,21015,39.504385,-76.327541,"Harford County, Maryland",17.45
105,Lorien Bulle Rock,1501 Blenheim Farm Lane,Havre de Grace,MD,21078,39.472912,-76.237938,"Harford County, Maryland",17.45
106,Lorien Nursing and Rehabilitation Center Columb,6334 Cedar Lane,Columbia,MD,21044,39.197084,-76.884686,"Howard County, Maryland",15.25
107,Ellicott City Healthcare Center,3000 N. Ridge Road,Ellicott City,MD,21043,39.290115,-76.819933,"Howard County, Maryland",15.25
108,Residences at Vantage Point,5400 Vantage Point Road,Columbia,MD,21044,39.223955,-76.855698,"Howard County, Maryland",15.25
109,Encore at Turf Valley,11150 Resort Road,Ellicott City,MD,21042,39.299695,-76.896284,"Howard County, Maryland",15.25
110,Lorien Nursing and Rehabilitation Center -Elkri,7615 Washington Blvd,Elkridge,MD,21075,39.177437,-76.773264,"Howard County, Maryland",15.25
111,The Lutheran Village At Miller''s Grant,9000 Fathers Legacy,Ellicott City,MD,21042,39.273918,-76.842447,"Howard County, Maryland",15.25
112,Resorts at Chester River Manor,200 Morgnec Road,Chestertown,MD,21620,39.224164,-76.066279,"Kent County, Maryland",27.42
113,Heron Point of Chestertown,501 East Campus Avenue,Chestertown,MD,21620,39.218207,-76.058470,"Kent County, Maryland",27.42
114,Chestertown Nursing and Rehab,415 Morgnec Road,Chestertown,MD,21620,39.224425,-76.063363,"Kent County, Maryland",27.42
115,Althea Woodland Nursing Home,1000 Daleview Drive,Silver Spring,MD,20901,39.008780,-76.992064,"Montgomery County, Maryland",16.99
116,Bel Pre Health & Rehab. Ctr.,2601 Bel Pre Road,Silver Spring,MD,20906,39.090435,-77.053583,"Montgomery County, Maryland",16.99
117,Autumn Lake Healthcare at Chevy Chase,8700 Jones Mill Road,Chevy Chase,MD,20815,38.998733,-77.065954,"Montgomery County, Maryland",16.99
118,Brooke Grove Rehabilitation and Nursing Center,18131 Slade School Road,Sandy Spring,MD,20860,39.154034,-77.040324,"Montgomery County, Maryland",16.99
119,Regency Care of Silver Spring,9101 Second Avenue,Silver Spring,MD,20910,39.004867,-77.041793,"Montgomery County, Maryland",16.99
120,Summit Hills MD OPCO LLC (Fox Chase),2015 East West Highway,Silver Spring,MD,20910,38.994924,-77.043576,"Montgomery County, Maryland",16.99
121,Shady Grove Center for Nursing & Rehabilitation,9701 Medical Center Drive,Rockville,MD,20850,39.101605,-77.195610,"Montgomery County, Maryland",16.99
122,Complete Care-Springbrook,12325 New Hampshire Avenue,Silver Spring,MD,20904,39.058646,-76.997513,"Montgomery County, Maryland",16.99
123,Genesis Fairland Center,2101 Fairland Road,Silver Spring,MD,20904,39.077011,-76.968109,"Montgomery County, Maryland",16.99
124,Friends House Retirement Community,17401 Norwood Road,Sandy Spring,MD,20860,39.139784,-77.031840,"Montgomery County, Maryland",16.99
125,Sterling Bethesda Health and Rehabilitation Cen,5721 Grosvenor Lane,Bethesda,MD,20814,39.022678,-77.114126,"Montgomery County, Maryland",16.99
126,Hebrew Home at Greater Washington,6121 Montrose Road,Rockville,MD,20852,39.052737,-77.123436,"Montgomery County, Maryland",16.99
127,Kensington Healthcare Center,3000 McComas Avenue,Kensington,MD,20895,39.032875,-77.060989,"Montgomery County, Maryland",16.99
128,Wheaton Operator LLC,11901 Georgia Avenue,Wheaton,MD,20902,39.050669,-77.051476,"Montgomery County, Maryland",16.99
129,Sterling Care Rockville Nursing Home,303 Adclare,Rockville,MD,20850,39.083229,-77.169744,"Montgomery County, Maryland",16.99
130,Carriage Hill Bethesda,5215 W. Cedar Lane,Bethesda,MD,20814,39.005540,-77.102944,"Montgomery County, Maryland",16.99
131,Herman M. Wilson Health Care Center,301 Russell Avenue,Gaithersburg,MD,20877,39.147703,-77.198714,"Montgomery County, Maryland",16.99
132,Potomac Valley Rehabilitation and Healthcare,1235 Potomac Valley Road,Rockville,MD,20850,39.074072,-77.160406,"Montgomery County, Maryland",16.99
133,Complete Care at Wheaton,4011 Randolph Road,Silver Springs,MD,20902,39.057650,-77.078105,"Montgomery County, Maryland",16.99
134,Sligo Creek Healthcare,7525 Carroll Avenue,Takoma Park,MD,20912,38.982104,-77.001854,"Montgomery County, Maryland",16.99
135,Autumn Lake Healthcare at Oakview,2700 Barker Street,Silver Spring,MD,20910,39.021500,-77.057400,"Montgomery County, Maryland",16.99
136,Autumn Lake Healthcare at Arcola,901 Arcola Avenue,Silver Spring,MD,20902,39.035624,-77.025828,"Montgomery County, Maryland",16.99
137,Montcare Bethesda,6530 Democracy Boulevard,Bethesda,MD,20817,39.022760,-77.132407,"Montgomery County, Maryland",16.99
138,"The Village at Rockville, Inc.",9701 Veirs Drive,Rockville,MD,20850,39.077351,-77.196032,"Montgomery County, Maryland",16.99
139,Layhill SNF LLC,3227 Bel Pre Road,Silver Spring,MD,20906,39.091429,-77.063384,"Montgomery County, Maryland",16.99
140,Montcare At Potomac,10714 Potomac Tennis Lane,Potomac,MD,20854,39.030853,-77.201549,"Montgomery County, Maryland",16.99
141,Autumn Lake Healthcare at Silver Spring,2501 Musgrove Road,Silver Spring,MD,20904,39.067726,-76.959123,"Montgomery County, Maryland",16.99
142,Bedford Court Sunrise Senior Living Services,3700 International Drive,Silver Spring,MD,20906,39.103591,-77.075039,"Montgomery County, Maryland",16.99
143,Montgomery Village Health Care Center,19301 Watkins Mill Road,Montgomery Village,MD,20886,39.172327,-77.208372,"Montgomery County, Maryland",16.99
144,Collingswood Nursing and Rehabilitation Center,299 Hurley Avenue,Rockville,MD,20850,39.087913,-77.179126,"Montgomery County, Maryland",16.99
145,Maplewood Park Place,9707 Old Georgetown Road,Bethesda,MD,20814,39.013258,-77.117294,"Montgomery County, Maryland",16.99
146,Ingleside at King Farm,701 King Farm Boulevard,Rockville,MD,20850,39.112316,-77.178852,"Montgomery County, Maryland",16.99
147,Autumn Lake Healthcare at Oak Manor,3415 Greencastle Road,Burtonsville,MD,20866,39.097025,-76.941387,"Montgomery County, Maryland",16.99
148,Tuckerman Rehabilitation and Health Care Center,5550 Tuckerman Lane,Bethesda,MD,20852,39.029815,-77.112630,"Montgomery County, Maryland",16.99
149,Clinton Healthcare Center,9211 Stuart Lane,Clinton,MD,20735,38.762982,-76.883786,"Prince George's County, Maryland",14.91
150,Complete Care at Hyattsville,4922 LaSalle Road,Hyattsville,MD,20782,38.951758,-76.977773,"Prince George's County, Maryland",14.91

In [11]:
#Number of nursing homes by county
nursing_homes_by_county=nursing_homes_df['County'].value_counts()

In [12]:
#Number of nursing homes by county x pct of 65+ per county 
%run lang-broad-county-S1601-cleaning.ipynb

In [13]:
languages_lep_pct_moe_df_long_wide['Geographic Area Name'].unique().tolist()

['Allegany County, Maryland',
 'Anne Arundel County, Maryland',
 'Baltimore County, Maryland',
 'Baltimore city, Maryland',
 'Calvert County, Maryland',
 'Caroline County, Maryland',
 'Carroll County, Maryland',
 'Cecil County, Maryland',
 'Charles County, Maryland',
 'Dorchester County, Maryland',
 'Frederick County, Maryland',
 'Garrett County, Maryland',
 'Harford County, Maryland',
 'Howard County, Maryland',
 'Kent County, Maryland',
 'Montgomery County, Maryland',
 "Prince George's County, Maryland",
 "Queen Anne's County, Maryland",
 'Somerset County, Maryland',
 "St. Mary's County, Maryland",
 'Talbot County, Maryland',
 'Washington County, Maryland',
 'Wicomico County, Maryland',
 'Worcester County, Maryland']

In [14]:
nursing_homes_df=nursing_homes_df.replace({'Baltimore County': 'Baltimore County, Maryland', 
                                    'Montgomery County': 'Montgomery County, Maryland',
                                   'Baltimore City': 'Baltimore city, Maryland',
                                    "Prince George's County":"Prince George's County, Maryland",
                                    'Anne Arundel County': 'Anne Arundel County, Maryland',
                                    'Frederick County':'Frederick County, Maryland',         
                                    'Washington County':'Washington County, Maryland',
                                    'Allegany County':'Allegany County, Maryland', 
                                    'Carroll County':'Carroll County, Maryland',         
                                    'Harford County':'Harford County, Maryland',
                                    'Howard County':'Howard County, Maryland',              
                                    'Charles County':'Charles County, Maryland',             
                                    'Garrett County':'Garrett County, Maryland',
                                    'Wicomico County':'Wicomico County, Maryland',
                                    'Calvert County':'Calvert County, Maryland',
                                    'Cecil County':'Cecil County, Maryland',
                                    'Kent County':'Kent County, Maryland',             
                                    "Saint Mary's County": "St. Mary's County, Maryland",
                                    'Worcester County':'Worcester County, Maryland',
                                    'Caroline County': 'Caroline County, Maryland',
                                    'Dorchester County':'Dorchester County, Maryland',
                                    'Somerset County':'Somerset County, Maryland',
                                    'Talbot County': 'Talbot County, Maryland',
                                   "Queen Anne's County": "Queen Anne's County, Maryland"})

In [15]:
nursing_homes_df=nursing_homes_df.rename({'County': 'Geographic Area Name'}, axis =1)

In [16]:
nursing_homes_df=nursing_homes_df.merge(languages_lep_pct_moe_df_long_wide[['Geographic Area Name', 'total_65_pct']],
                                        on='Geographic Area Name',
                                        how='left')

In [19]:
nursing_homes_by_county.to_csv("nursing_homes_by_county.csv")
nursing_homes_df.to_csv("nursing_homes_df.csv")

In [22]:
nursing_homes_df.columns

Index(['Current Name', 'Facility Street1', 'Facility City', 'Facility State',
       'Zip Code', 'Latitude', 'Longitude', 'Geographic Area Name',
       'total_65_pct'],
      dtype='str')

In [30]:
nursing_homes_by_county_df = (nursing_homes_df
    .groupby('Geographic Area Name')
    .agg(nursing_homes_count=('Current Name', 'count'),
        total_65_pct=('total_65_pct', 'first'))
    .reset_index())

In [33]:
nursing_homes_by_county_df['nursing_homes_count'].median()

np.float64(4.0)

In [32]:
nursing_homes_by_county_df.to_csv("nursing_homes_by_county_df.csv")

In [36]:
nursing_homes_df_viz = nursing_homes_df.copy()

In [41]:
nursing_homes_df_viz['Geographic Area Name'] = (nursing_homes_df_viz['Geographic Area Name'].str.replace(', Maryland', ''))

In [47]:
nursing_homes_df_viz=nursing_homes_df_viz.drop(columns=["Facility State", "Latitude", "Longitude", "total_65_pct"])

In [48]:
nursing_homes_df_viz.to_csv("nursing_homes_df_viz.csv")

In [57]:
nursing_homes_df_viz[nursing_homes_df_viz['Geographic Area Name'] == "Montgomery County"]

,Current Name,Facility Street1,Facility City,Zip Code,Geographic Area Name
115,Althea Woodland Nursing Home,1000 Daleview Drive,Silver Spring,20901,Montgomery County
116,Bel Pre Health & Rehab. Ctr.,2601 Bel Pre Road,Silver Spring,20906,Montgomery County
117,Autumn Lake Healthcare at Chevy Chase,8700 Jones Mill Road,Chevy Chase,20815,Montgomery County
118,Brooke Grove Rehabilitation and Nursing Center,18131 Slade School Road,Sandy Spring,20860,Montgomery County
119,Regency Care of Silver Spring,9101 Second Avenue,Silver Spring,20910,Montgomery County
120,Summit Hills MD OPCO LLC (Fox Chase),2015 East West Highway,Silver Spring,20910,Montgomery County
121,Shady Grove Center for Nursing & Rehabilitation,9701 Medical Center Drive,Rockville,20850,Montgomery County
122,Complete Care-Springbrook,12325 New Hampshire Avenue,Silver Spring,20904,Montgomery County
123,Genesis Fairland Center,2101 Fairland Road,Silver Spring,20904,Montgomery County
124,Friends House Retirement Community,17401 Norwood Road,Sandy Spring,20860,Montgomery County
125,Sterling Bethesda Health and Rehabilitation Cen,5721 Grosvenor Lane,Bethesda,20814,Montgomery County
126,Hebrew Home at Greater Washington,6121 Montrose Road,Rockville,20852,Montgomery County
127,Kensington Healthcare Center,3000 McComas Avenue,Kensington,20895,Montgomery County
128,Wheaton Operator LLC,11901 Georgia Avenue,Wheaton,20902,Montgomery County
129,Sterling Care Rockville Nursing Home,303 Adclare,Rockville,20850,Montgomery County
130,Carriage Hill Bethesda,5215 W. Cedar Lane,Bethesda,20814,Montgomery County
131,Herman M. Wilson Health Care Center,301 Russell Avenue,Gaithersburg,20877,Montgomery County
132,Potomac Valley Rehabilitation and Healthcare,1235 Potomac Valley Road,Rockville,20850,Montgomery County
133,Complete Care at Wheaton,4011 Randolph Road,Silver Springs,20902,Montgomery County
134,Sligo Creek Healthcare,7525 Carroll Avenue,Takoma Park,20912,Montgomery County
135,Autumn Lake Healthcare at Oakview,2700 Barker Street,Silver Spring,20910,Montgomery County
136,Autumn Lake Healthcare at Arcola,901 Arcola Avenue,Silver Spring,20902,Montgomery County
137,Montcare Bethesda,6530 Democracy Boulevard,Bethesda,20817,Montgomery County
138,"The Village at Rockville, Inc.",9701 Veirs Drive,Rockville,20850,Montgomery County
139,Layhill SNF LLC,3227 Bel Pre Road,Silver Spring,20906,Montgomery County
140,Montcare At Potomac,10714 Potomac Tennis Lane,Potomac,20854,Montgomery County
141,Autumn Lake Healthcare at Silver Spring,2501 Musgrove Road,Silver Spring,20904,Montgomery County
142,Bedford Court Sunrise Senior Living Services,3700 International Drive,Silver Spring,20906,Montgomery County
143,Montgomery Village Health Care Center,19301 Watkins Mill Road,Montgomery Village,20886,Montgomery County
144,Collingswood Nursing and Rehabilitation Center,299 Hurley Avenue,Rockville,20850,Montgomery County
145,Maplewood Park Place,9707 Old Georgetown Road,Bethesda,20814,Montgomery County
146,Ingleside at King Farm,701 King Farm Boulevard,Rockville,20850,Montgomery County
147,Autumn Lake Healthcare at Oak Manor,3415 Greencastle Road,Burtonsville,20866,Montgomery County
148,Tuckerman Rehabilitation and Health Care Center,5550 Tuckerman Lane,Bethesda,20852,Montgomery County
165,Riderwood Village,3160 Gracefield Road,Silver Spring,20904,Montgomery County